language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then pip install --use-mirrors matplotlib; fi'
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then sudo apt-get install -qq python-numpy python-matplotlib; fi'
script:
  - nosetests
