language: python
python:
  - "2.7"
  - "3.3"
virtualenv:
  system_site_packages: true
install:
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then sudo apt-get install -qq python3-numpy python3-scipy; pip install matplotlib --use-mirrors fi'
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then sudo apt-get install -qq python-numpy python-scipy python-matplotlib; fi'
script:
  - nosetests
